[package]
name = "async_trait"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ic-cdk.workspace = true
async-trait = "0.1"

[lib]
crate-type = ["cdylib"]
